language: node_js
node_js:
- 8.11.3
sudo: false
before_install:
- curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.9.4
- export PATH=$HOME/.yarn/bin:$PATH
cache:
  yarn: true
script:
- cd client && yarn && CI=false yarn build && mv build ../server && cd ..
- cd server && yarn && cd ..
# before_deploy:
# - env
deploy:
  provider: cloudfoundry
  api: https://api.run.pivotal.io
  username: slaytanic@gmail.com
  password:
    secure: YbrvukWgRPxA+0S+gVOz6Ww+Rj+lSLzDckxbS9szNM9KP0mXI2251KCUfkCe5MnlWJDnIRlhUJt3QoPFTeHrvdqtNHSIG4pIj6fBqjilEbJwtSN1BUrcxtuoap87WmHJYr+9uq5T1+aMfj6fuG0sycNyz26V4KfO8HLb9Upyp5OvME1hGE6P67GhL90YQs4D2uTxcy2u4QFBAueXTvZUyo6jN1Garj7FmKai9XFubapaRg1rH41fsitZikkCRcxVw25WHRe8WIl7AZmM4mI2A2gx9tVpA6h8df4tbjW6luIETiANUpUl62eUm6LpGmAL1yLWYPoAJWLTfvlM9/mDrmmMvSgz+Pn+j/BT1KFgwq8wL3wBonVvBDBDcviomT5sBJVVyUEvz8IrqjQGB53HXsJvg3f6Syz2QST1tQu4AH3hUkea2QIl+9wXKenw1WkkWzE6l23LcGS+UpmP5mAMr3MOdEnB9jZy9CGgWzpBJl1OlLUBDfxkWYzmgrV80yarg2w5kpyZN0DK3csG533yYOXedrBMQCAgBztwFLugeT0x1oEC+mgQ3BWaUpbkWS5t58kq0pbCYIp6z0AZ40J5QjVtvvd6/bn5YEsOKqfjDJB5ygTwFag9F/M6eHOL02oL9fobcfisRuqwodz/B+OQIC5EaQdTogSwh13dNRHMxXk=
  organization: MiFADU
  space: development
  # provider: script
  # script:
  # - cf login -a $CF_API -u $CF_USERNAME -p $CF_PASSWORD -o $CF_ORG -s $CF_SPACE
  # - cf push $CF_APP
  skip_cleanup: true
  on:
    branch:
    - master
    - legacy
# env:
#   global:
#     - CF_API=https://api.run.pivotal.io
#     - CF_ORG=MiFADU
#     - CF_SPACE=development
#     - CF_USERNAME=slaytanic@gmail.com
#     secure: mts8s/CsERDPlKZOHLj1FDBOoxYyysHNO4ylmU8l2Iu0ACiabbupduFBCaiiC2B7mEoXZH1YYKtJqRBh5Qc5ViLKqQ2/ogY5vILsuBox/CTgSyGApQnaBi4BCh81M7wQSVGYARKebXISGexVsZPoX9RKy0FzxMgnJ74R038PYjRFwSg/dq2+1/QGMQRsYcOL2dHVQWFuPMrJSNTgYta5DGs066ap2AHTEThuS65hf2fupvzdpP4NJBC6ApXoM3Q90pf4wAFCtHdbZwzaTkXTytGGvIcGJ8Z5PhA7JL/Gwj1lQEKECGACSmayQxpBwENAui/uxb718xloKo+r7VR28iRct5En0ZFu/0u0e9IllKgHsvCfUgBRwYrj5Br3wI3wyucIhZlmnSCAVdu80PY8PALpM7td+udHixnjDfGEg0iwvdZ2nTd4zrPJon6pXIDPtdB80P+Svfi0ABI/ur4UnNOQ00WOzCWPFhiAD3EhnMGdTPZruZ4QjbHcv4tTRHecSx8A2j2UeDXnpBwzthnMCduTCcOqMmC9nZhNgKUZrWkKxmqTRncrB/Q6Qt83elbX91YFvhj6p5fASuPpt3jTKC+2KdhiDJ+p37NwwdcYHoVbuGfaPp4k9Yl/jrF2A9DvlmDdFh4O1wPC10ei0QDyE19BTIYi+WjuBjis8SFaQHY=
