language: node_js
node_js:
- 10.15.2
sudo: false
dist: xenial
before_install:
- curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.12.3
- export PATH=$HOME/.yarn/bin:$PATH
cache:
  yarn: true
script:
- cd client && yarn && CI=false yarn build && mv build ../server && cd ..
- cd server && yarn && cd ..
deploy:
- provider: cloudfoundry
  api: https://api.run.pivotal.io
  username: carlos.monti+mifadu@gmail.com
  password:
    secure: i0AGtpompBGUIHF2ePLzHGb55TihIKlLj4gSD2rBnLqOqdfM4XRmq2yUabsMsde5Rq9AYYAO86B09pErSqA8JlVmJOt0+AdaS/Ejxr/I4HByNU0odlx08IRUKnrZdUB9OzNzM0a3CXm5DGesFsE9NuDS5az6HFQzahE3lZwT+wYcSKX7ab1ITuBOuveqfpgMzOqhMGi+Sd+f93oxTdAA+Zfv4GEsDMwuYQ4uWaBwWlPMmXiZVLfhURbhREyzdcYAd/2TakV8LYxUZ74y9v5SDe5zDQSx6n4AM/vBsWcBDvuTH5zED/lb497ZMn49q9SkY5F2ait/Wc4sPILR7rcYE6NgAoy9sDjfcwL1lqren9IwJdUGEbwhCduAUzbpzpH9QAg1lv1kF9ZZ2owIjv1q+N+txfeRzdWjrWrUsfrqmxAHOiC2B2CFGRIajSMKoz+yYl9XOgSDPToKkJxtJiWL9pAxny0tLT4ROH0z5cL0ZzDROZ3dOoZj18bMStsYQQHoqjfQQYzunHGq/cxzk9QARxtalR4JVSp4T1XENg2QfGzoZtBSOjLRj5nU/p2qy+vDGECPVkvuZaSSA93hglTt4njWm2WVJFa6wt3CUiXOsUGyo/sCNXLm3W18THPLRS7B/+34UtLjPhA4Kz9dkNwY5EeztskuApLGOVwjDMBV0sg=
  organization: MiFADU
  space: development
  skip_cleanup: true
  manifest: manifest-beta.yml
  on:
    branch:
    - beta
- provider: cloudfoundry
  api: https://api.run.pivotal.io
  username: carlos.monti+mifadu@gmail.com
  password:
    secure: i0AGtpompBGUIHF2ePLzHGb55TihIKlLj4gSD2rBnLqOqdfM4XRmq2yUabsMsde5Rq9AYYAO86B09pErSqA8JlVmJOt0+AdaS/Ejxr/I4HByNU0odlx08IRUKnrZdUB9OzNzM0a3CXm5DGesFsE9NuDS5az6HFQzahE3lZwT+wYcSKX7ab1ITuBOuveqfpgMzOqhMGi+Sd+f93oxTdAA+Zfv4GEsDMwuYQ4uWaBwWlPMmXiZVLfhURbhREyzdcYAd/2TakV8LYxUZ74y9v5SDe5zDQSx6n4AM/vBsWcBDvuTH5zED/lb497ZMn49q9SkY5F2ait/Wc4sPILR7rcYE6NgAoy9sDjfcwL1lqren9IwJdUGEbwhCduAUzbpzpH9QAg1lv1kF9ZZ2owIjv1q+N+txfeRzdWjrWrUsfrqmxAHOiC2B2CFGRIajSMKoz+yYl9XOgSDPToKkJxtJiWL9pAxny0tLT4ROH0z5cL0ZzDROZ3dOoZj18bMStsYQQHoqjfQQYzunHGq/cxzk9QARxtalR4JVSp4T1XENg2QfGzoZtBSOjLRj5nU/p2qy+vDGECPVkvuZaSSA93hglTt4njWm2WVJFa6wt3CUiXOsUGyo/sCNXLm3W18THPLRS7B/+34UtLjPhA4Kz9dkNwY5EeztskuApLGOVwjDMBV0sg=
  organization: MiFADU
  space: development
  skip_cleanup: true
  on:
    branch:
    - master
