language: node_js
node_js:
- 8.11.3
sudo: false
before_install:
- curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.9.4
- export PATH=$HOME/.yarn/bin:$PATH
cache:
  yarn: true
script:
- cd client && yarn && CI=false yarn build && mv build ../server && cd ..
- cd server && yarn && cd ..
deploy:
  provider: cloudfoundry
  api: https://api.run.pivotal.io
  username: slaytanic@gmail.com
  password:
    secure: FIoe5dWRU8F0xY0B1zIcn5qOtveqA6r0cPgLJYT3CpSYiwfArFymUYSYRsruBgwe+slsO5EBSf4VxQcmBLo0IKDla6FWvrQBvibJJ0ufuRyQ+PdvT4fRDZvo+wOMogN6C2YDXue+FlGNElK6TY2k2hMJPUgAz9tnLa2dGYm5dtJIevOqb0PX0Nsu0I1YRgTXmHPqav8YAR8OuAhMMol/6gtFrSVAnKlErVfNskr8Vg1pj5CGMT5nPNyU3tBAYe074T4z4ctX0/761oLJ3llSvkKQhw+LCfWddpxM1PRwCKHnCStkYUC7cJerhPyPm8D4kO6AQiHl5gNhvnrIfaTkGA7fun9r94H3WdjFErcBMxks4wMDgnBnwb/xZCuG+ZNvg1R5sLi3WoUSaXoj6nrmFKinTcr+Ui1TK/vP6NUOHIs5HAlzrNy+x9O9tBQ1fgbsUcyxdTLows3A4XhraiAba9y4QGUTZ/dqFNNp1a/eb1hpVD81M9odjQmTE8na0nT7fJ+PcFunLt4zWgipao8Lrg7pUKexVg+uGVl+RK4QId8zjdQ6GORO/Xoi4z2MfYIfymHem5g05gnaTzab9pevuVL03DcnVgqVjFAiT59PW2wb/ra67+Yzgo9Ij0g/XgDy6YUnT1N/J4MglNsk2/EcxsLaUfQFebpReIuJEm+qpmw=
  organization: MiFADU
  space: development
  skip_cleanup: true
  on:
    branch: master
