language: node_js
node_js:
- 8.11.3
sudo: false
before_install:
- curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.9.4
- export PATH=$HOME/.yarn/bin:$PATH
cache:
  yarn: true
script:
- cd client && yarn && CI=false yarn build && mv build ../server && cd ..
- cd server && yarn && cd ..
deploy:
  provider: cloudfoundry
  api: https://api.run.pivotal.io
  username: slaytanic@gmail.com
  password:
    secure: ozBX+87nzolA9BZUkxSpnrgIyiQhgNU+JpJDp7eX9qy0CyM0fKvC/H4YC9qlN/6NNbIFJ6+Fl4owhMIpWcFB12uRQgWdoTF6jF5DHKOvOalD/T1qVVexOhfFqVCAdTP+Ll28uww9Uup8Ohs+P6vG2mxlh9k/I/OOjeBMoev8Z3cfM/1JnxSxSHXVuq4JHxXtUZ2h1PsNPEcYKHLl5CQjMsbraEjcpS1Ty1MXtD1iM1bL10oUZSOS5xWN4Yph4JO8ERIBmGIiBnI2DLwq3Q+gGysA0z6nXMDcwGvpUJ7LeCvd/MCDBdhhVUF3qMoUaKVtCf3bdHVAj5iB4cDOE+RgDyQcsQT3yuiwLSgUexivBpd+pdVF25Rb9TqY4nTMvdDa+b6zo+tk1AVXl49FB/ZuifR4B7eTiP8+3p1r1a3d1vpcMOzsnHF8B3IhFklGrpCNZ4JrBkGOXAvAhGDnO4EilOo6yekdBPjFBy5ffIILIDDdHMZ4SsJ5SFhGtQAcrkUf3SHd4WazTsk6SAVJvqH/6Hd8L6IOs+X20FbzzEXgXGLFW8IS6yMhYWPscL+N+xMw6c0MLnxkKuMz9ebEt0R/Ufld4C1Uf5QaeH+A6eNy3njBMPQyHtyFw0n65rAPaoS0bkd8JYe/3m/RHh396xvjZaB0GHQVKHJpgFkZph/0Mog=
  organization: MiFADU
  space: development
  skip_cleanup: true
  on:
    branch: master
