export const CURRENT_USER_IS_LOADING = 'CURRENT_USER_IS_LOADING';
export const CURRENT_USER_HAS_LOADED = 'CURRENT_USER_HAS_LOADED';
export const CURRENT_USER_HAS_ERRORED = 'CURRENT_USER_HAS_ERRORED';
export const FETCH_CURRENT_USER = 'FETCH_CURRENT_USER';
export const LOGIN_USER = 'LOGIN_USER';
export const LOGOUT_USER = 'LOGOUT_USER';
export const REGISTER_USER = 'REGISTER_USER';

export const USERS_IS_LOADING = 'USERS_IS_LOADING';
export const USERS_HAS_LOADED = 'USERS_HAS_LOADED';
export const FETCH_USERS = 'FETCH_USERS';
export const CREATE_USER = 'CREATE_USER';
export const UPDATE_USER = 'UPDATE_USER';
export const DELETE_USER = 'DELETE_USER';

export const WORKSHOPS_IS_LOADING = 'WORKSHOPS_IS_LOADING';
export const WORKSHOPS_HAS_LOADED = 'WORKSHOPS_HAS_LOADED';
export const FETCH_WORKSHOPS = 'FETCH_WORKSHOPS';
export const CREATE_WORKSHOP = 'CREATE_WORKSHOP';
export const UPDATE_WORKSHOP = 'UPDATE_WORKSHOP';
export const DELETE_WORKSHOP = 'DELETE_WORKSHOP';

export const SUBJECTS_IS_LOADING = 'SUBJECTS_IS_LOADING';
export const SUBJECTS_HAS_LOADED = 'SUBJECTS_HAS_LOADED';
export const FETCH_SUBJECTS = 'FETCH_SUBJECTS';
export const CREATE_SUBJECT = 'CREATE_SUBJECT';
export const UPDATE_SUBJECT = 'UPDATE_SUBJECT';
export const DELETE_SUBJECT = 'DELETE_SUBJECT';

export const TAGS_IS_LOADING = 'TAGS_IS_LOADING';
export const TAGS_HAS_LOADED = 'TAGS_HAS_LOADED';
export const TAG_CREATED = 'TAG_CREATED';
export const TAG_UPDATED = 'TAG_UPDATED';
export const TAG_DELETED = 'TAG_DELETED';
export const FETCH_TAGS = 'FETCH_TAGS';

export const STUDENTS_IS_LOADING = 'STUDENTS_IS_LOADING';
export const STUDENTS_HAS_LOADED = 'STUDENTS_HAS_LOADED';
export const FETCH_STUDENTS = 'FETCH_STUDENTS';

export const ASSIGNMENTS_IS_LOADING = 'ASSIGNMENTS_IS_LOADING';
export const ASSIGNMENTS_HAS_LOADED = 'ASSIGNMENTS_HAS_LOADED';
export const ASSIGNMENT_HAS_LOADED = 'ASSIGNMENT_HAS_LOADED';
export const ASSIGNMENT_CREATED = 'ASSIGNMENT_CREATED';
export const ASSIGNMENT_UPDATED = 'ASSIGNMENT_UPDATED';
export const ASSIGNMENT_DELETED = 'ASSIGNMENT_DELETED';
export const FETCH_ASSIGNMENTS = 'FETCH_ASSIGNMENTS';
