const subjects = [
  { code: 'AP', name: 'Análisis de Productos' },
  { code: 'DI1', name: 'Diseño Industrial I' },
  { code: 'DI2', name: 'Diseño Industrial II' },
  { code: 'DI3', name: 'Diseño Industrial III' },
  { code: 'DI4', name: 'Diseño Industrial IV' },
  { code: 'DI5', name: 'Diseño Industrial V' },
  { code: 'ERG', name: 'Ergonomía' },
  { code: 'F1', name: 'Física I' },
  { code: 'F2', name: 'Física II' },
  { code: 'HDI', name: 'Historia del Diseño Industrial' },
  { code: 'IA', name: 'Industria Argentina' },
  { code: 'IDAM', name: 'Introducción al Diseño y a la Arquitectura Moderna' },
  { code: 'L', name: 'Legislación y Práctica Profesional' },
  { code: 'MAT', name: 'Matemática I' },
  { code: 'M', name: 'Morfología' },
  { code: 'ME1', name: 'Morfología Especial I' },
  { code: 'ME2', name: 'Morfología Especial II' },
  { code: 'MET', name: 'Metodología' },
  { code: 'SAD', name: 'Sociología aplicada al Diseño' },
  { code: 'T1', name: 'Tecnología I' },
  { code: 'T2', name: 'Tecnología II' },
  { code: 'T3', name: 'Tecnología III' },
  { code: 'T4', name: 'Tecnología IV' },
  { code: 'DI', name: 'Materias Optativas I' },
  { code: 'DI', name: 'Materias Optativas II' },
];

module.exports = subjects;
