export const CURRENT_USER_IS_LOADING = 'CURRENT_USER_IS_LOADING';
export const CURRENT_USER_HAS_LOADED = 'CURRENT_USER_HAS_LOADED';
export const FETCH_CURRENT_USER = 'FETCH_CURRENT_USER';
export const LOGIN_USER = 'LOGIN_USER';
export const LOGOUT_USER = 'LOGOUT_USER';
export const REGISTER_USER = 'REGISTER_USER';

export const USERS_IS_LOADING = 'USERS_IS_LOADING';
export const USERS_HAS_LOADED = 'USERS_HAS_LOADED';
export const FETCH_USERS = 'FETCH_USERS';
export const CREATE_USER = 'CREATE_USER';
export const UPDATE_USER = 'UPDATE_USER';
export const DELETE_USER = 'DELETE_USER';

export const WORKSHOPS_IS_LOADING = 'WORKSHOPS_IS_LOADING';
export const WORKSHOPS_HAS_LOADED = 'WORKSHOPS_HAS_LOADED';
export const FETCH_WORKSHOPS = 'FETCH_WORKSHOPS';
export const CREATE_WORKSHOP = 'CREATE_WORKSHOP';
export const UPDATE_WORKSHOP = 'UPDATE_WORKSHOP';
export const DELETE_WORKSHOP = 'DELETE_WORKSHOP';

export const SUBJECTS_IS_LOADING = 'SUBJECTS_IS_LOADING';
export const SUBJECTS_HAS_LOADED = 'SUBJECTS_HAS_LOADED';
export const FETCH_SUBJECTS = 'FETCH_SUBJECTS';
export const CREATE_SUBJECT = 'CREATE_SUBJECT';
export const UPDATE_SUBJECT = 'UPDATE_SUBJECT';
export const DELETE_SUBJECT = 'DELETE_SUBJECT';

export const TAGS_IS_LOADING = 'TAGS_IS_LOADING';
export const TAGS_HAS_LOADED = 'TAGS_HAS_LOADED';
export const FETCH_TAGS = 'FETCH_TAGS';
export const CREATE_TAG = 'CREATE_TAG';
export const UPDATE_TAG = 'UPDATE_TAG';
export const DELETE_TAG = 'DELETE_TAG';

export const ASSIGNMENTS_IS_LOADING = 'ASSIGNMENTS_IS_LOADING';
export const ASSIGNMENTS_HAS_LOADED = 'ASSIGNMENTS_HAS_LOADED';
export const ASSIGNMENT_DELETED = 'ASSIGNMENT_DELETED';
export const FETCH_ASSIGNMENTS = 'FETCH_ASSIGNMENTS';
export const CREATE_ASSIGNMENT = 'CREATE_ASSIGNMENT';
export const UPDATE_ASSIGNMENT = 'UPDATE_ASSIGNMENT';
export const DELETE_ASSIGNMENT = 'DELETE_ASSIGNMENT';
export const SUBMIT_ASSIGNMENT = 'SUBMIT_ASSIGNMENT';
export const SCORE_ASSIGNMENT = 'SCORE_ASSIGNMENT';
